name: 'Terraform, Build, Deploy (production)'

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}  # Prevents more than one instance of this workflow running at the same time

jobs:
  terraform_build_deploy:
    uses: ./.github/workflows/_build-and-deploy-shared.yml
    with:
      GITHUB_ACTIONS_ENVIRONMENT: Prod
      TERRAFORM_SERVICE_NAME: smc_web
      TERRAFORM_SERVICE_NAME_HYPHENS: smc-web
      TERRAFORM_ENVIRONMENT_NAME: Prod
      TERRAFORM_STATE_BUCKET: uk-gov-equality-hub-terraform-state-bucket
      TERRAFORM_STATE_FILE: smc-website--prod.tfstate
      TERRAFORM_TFVARS_FILE: prod.tfvars
    secrets:
      TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
      TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
